name: Feature Request
description: Add a feature request
title: "Feature Request: "
body:
  - type: markdown
    attributes:
      value: | 
        Thank you for being an awesome part of our community and for taking the time to share your ideas with us.
        We can't express enough how grateful we are for your effort in helping us make our products even better.
        Your input is crucial in our mission to enhance our products and provide a better experience for all our customers.
  - type: textarea
    id: request
    attributes:
      label: The feature request
      description: What kind of new feature would you like to see in our Tibber for Homey app and why? Please also describe a real life use case for your request and how it would make your experience with the app better.
    validations:
      required: true
  - type: markdown
    attributes:
      value: | 
        Thank you for taking the time to submitting a feature request!